-- GENERATED by scripts/mig/gen_bi_compat.py from db/pg/rename_map.yaml — do not edit by hand.
-- TEMPORARY read-only bridge so Superset datasets keep their legacy table/column names
-- ("ISIN", "window", ...) after repointing at the primary Postgres. Apply once, as the
-- schema owner, at cutover; DROP SCHEMA bi_compat CASCADE once datasets use the new names.

CREATE SCHEMA IF NOT EXISTS bi_compat;
GRANT USAGE ON SCHEMA bi_compat TO superset_ro;

CREATE OR REPLACE VIEW bi_compat.fund_master AS
SELECT
       "isin" AS "ISIN",
       "fund_name" AS "Fund_Name",
       "management_company" AS "Management_Company",
       "fund_nature" AS "Fund_Nature",
       "profile" AS "Profile",
       "vehicle_structure" AS "Vehicle_Structure",
       "family" AS "Family",
       "style_profile" AS "Style_Profile",
       "geography" AS "Geography",
       "theme" AS "Theme",
       "exposure_bias" AS "Exposure_Bias",
       "heuristic_block" AS "Heuristic_Block",
       "heuristic_core" AS "Heuristic_Core",
       "srri" AS "SRRI",
       "fund_currency" AS "Fund_Currency",
       "hedging_policy" AS "Hedging_Policy",
       "replication_method" AS "Replication_Method",
       "derivatives_usage" AS "Derivatives_Usage",
       "benchmark_declared" AS "Benchmark_Declared",
       "inference_trace" AS "Inference_Trace",
       "srri_quality_flag" AS "SRRI_Quality_Flag",
       "data_quality_flag" AS "Data_Quality_Flag",
       "created_at" AS "Created_At",
       "updated_at" AS "Updated_At",
       "ongoing_charge_recurrent" AS "Ongoing_Charge_Recurrent",
       "fund_family_id" AS "fund_family_id",
       "strategy" AS "Strategy",
       "benchmark_type" AS "Benchmark_Type",
       "accumulation_policy" AS "Accumulation_Policy",
       "entry_fee_pct" AS "Entry_Fee_Pct",
       "exit_fee_pct" AS "Exit_Fee_Pct",
       "sfdr_article" AS "Sfdr_Article",
       "recommended_holding_period" AS "Recommended_Holding_Period",
       "leverage_used" AS "Leverage_Used",
       "liquidity_profile" AS "Liquidity_Profile",
       "distribution_frequency" AS "Distribution_Frequency",
       "market_cap_focus" AS "Market_Cap_Focus",
       "sector_focus" AS "Sector_Focus",
       "investment_universe" AS "Investment_Universe",
       "investment_focus" AS "Investment_Focus",
       "credit_quality" AS "Credit_Quality",
       "fee_known_flag" AS "Fee_Known_Flag",
       "kid_format" AS "KID_Format",
       "kid_currency" AS "KID_Currency",
       "cost_extraction_quality" AS "Cost_Extraction_Quality",
       "cost_rhp_years" AS "Cost_RHP_Years",
       "entry_fee_pct_max" AS "Entry_Fee_Pct_Max",
       "exit_fee_pct_max" AS "Exit_Fee_Pct_Max",
       "management_fee_pct" AS "Management_Fee_Pct",
       "transaction_cost_pct" AS "Transaction_Cost_Pct",
       "performance_fee_pct" AS "Performance_Fee_Pct",
       "aci_1y" AS "ACI_1Y",
       "aci_rhp" AS "ACI_RHP",
       "development_status" AS "Development_Status",
       "duration_profile" AS "Duration_Profile",
       "mmf_structure" AS "MMF_Structure",
       "alt_strategy" AS "Alt_Strategy",
       "payoff_profile" AS "Payoff_Profile",
       "asset_currency" AS "Asset_Currency",
       "in_current_universe" AS "In_Current_Universe",
       "performance_fee_basis" AS "Performance_Fee_Basis"
FROM   silver.fund_master;
GRANT SELECT ON bi_compat.fund_master TO superset_ro;

CREATE OR REPLACE VIEW bi_compat.fund_metric_timeseries AS
SELECT
       "isin" AS "isin",
       "metric" AS "metric",
       "window_label" AS "window",
       "date" AS "date",
       "value" AS "value",
       "real_flag" AS "real_flag",
       "ref_type" AS "ref_type",
       "ref_value" AS "ref_value",
       "source_rows" AS "source_rows",
       "algorithm_version" AS "algorithm_version",
       "batch_id" AS "batch_id"
FROM   gold.fund_metric_timeseries;
GRANT SELECT ON bi_compat.fund_metric_timeseries TO superset_ro;

CREATE OR REPLACE VIEW bi_compat.fund_metric_alerts AS
SELECT
       "isin" AS "isin",
       "metric" AS "metric",
       "window_label" AS "window",
       "level" AS "level",
       "rule_code" AS "rule_code",
       "value" AS "value",
       "reference_value" AS "reference_value",
       "ref_type" AS "ref_type",
       "detected_at" AS "detected_at"
FROM   gold.fund_metric_alerts;
GRANT SELECT ON bi_compat.fund_metric_alerts TO superset_ro;
