# proyecto1/tests/test_data_quality_rollup_pg.py
# -*- coding: utf-8 -*-
"""
Postgres migration (addendum, 2026-09-20, plan §Addendum Stage 3) — dedicated regression tests for
core.pipeline._finalize_data_quality_issues() against real Postgres.

Companion to test_data_quality_rollup.py (SQLite, in-memory) — same logical cases, ported per the
migration's "port function and test together" discipline.

Uses `pg_conn` (SAVEPOINT, autocommit=False), NOT `pg_conn_module_schema` — deliberately, and only
after finding out why the obvious choice is wrong. `_finalize_data_quality_issues()` calls
`log_ingestion()` (sqlite_writer.py) for each issue, which issues a bare `SAVEPOINT` of its own —
valid SQL only when a transaction block is already open. Under real production
(`get_connection(backend="postgres")`, `autocommit=False` by default), psycopg3 auto-opens an
implicit transaction on the first statement of any new transaction, so this always holds — verified
live. But `pg_conn_module_schema` sets `conn.autocommit = True` for its *entire* yielded duration
(needed for its own `CREATE SCHEMA`), and autocommit mode never has an open transaction block at
all — every statement is its own committed unit. Tried that fixture first here; every test calling
`log_ingestion` failed with `psycopg.errors.NoActiveSqlTransaction: SAVEPOINT can only be used in
transaction blocks`. Verified in isolation (a standalone script, autocommit=False + an outer
SAVEPOINT, mirroring `pg_conn` exactly) that this is a test-fixture mismatch, not a production bug —
`_finalize_data_quality_issues()` itself needed no change. `pg_conn` is also simply the *correct*
fixture here per its own docstring: this function never calls `conn.commit()`/`conn.rollback()`, so
it's exactly the "create some tables, write some rows, assert, forget it happened" default case —
`pg_conn_module_schema` should be reserved for commit-owning functions, which this isn't.

create_schema() (used by the SQLite version to build its in-memory DB) deliberately raises under
Postgres (Postgres schema is provisioned externally via db/pg/*.sql, not autotranslated SQLite DDL
at runtime) — so this file hand-builds the two tables this function touches, matching
db/pg/20_silver.sql / db/pg/35_control.sql. They land in the connection's default search_path
(`public` for the superuser DSN used in dev/CI) — isolated from the real `silver`/`control`-schema
tables, and undone regardless by `pg_conn`'s always-rollback SAVEPOINT.

R-7 note: imports pipeline.py directly, same as the SQLite-side test in this same directory.
"""
from __future__ import annotations

import os
import sys

_TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
_CORE_DIR = os.path.normpath(os.path.join(_TESTS_DIR, "..", "core"))
_P1_DIR = os.path.normpath(os.path.join(_TESTS_DIR, ".."))
for _p in (_CORE_DIR, _P1_DIR):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from pipeline import _finalize_data_quality_issues  # noqa: E402


def _make_tables(conn):
    conn.execute("""
        CREATE TABLE fund_data_quality_issues (
            id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            isin          varchar(12) NOT NULL,
            check_code    text        NOT NULL,
            level         text        NOT NULL,
            message       text,
            detected_at   timestamptz
        )
    """)
    conn.execute("""
        CREATE TABLE ingestion_log (
            id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            isin       varchar(12),
            step       text,
            status     text,
            message    text,
            created_at timestamptz
        )
    """)


def test_no_issues_returns_base_level(pg_conn):
    _make_tables(pg_conn)
    assert _finalize_data_quality_issues(pg_conn, "LU_TEST_1", "OK", []) == "OK"


def test_single_warn_issue_upgrades_ok_base(pg_conn):
    _make_tables(pg_conn)
    issues = [("FUNDCCY_NAME_KIID_MISMATCH", "WARN", "WARN", "mismatch detectado")]
    assert _finalize_data_quality_issues(pg_conn, "LU_TEST_2", "OK", issues) == "WARN"


def test_inferred_does_not_downgrade_or_upgrade_past_warn(pg_conn):
    _make_tables(pg_conn)
    issues = [
        ("RC08_STRATEGY_INFERRED", "INFERRED", "INFO", "strategy inferida"),
        ("HEDGCCY_NO_MISMATCH_INCONSISTENCY", "WARN", "WARN", "hedge inconsistente"),
    ]
    assert _finalize_data_quality_issues(pg_conn, "LU_TEST_3", "OK", issues) == "WARN"


def test_missing_base_is_not_downgraded_by_a_later_inferred_issue(pg_conn):
    _make_tables(pg_conn)
    issues = [("RC08_STRATEGY_INFERRED", "INFERRED", "INFO", "strategy inferida")]
    assert _finalize_data_quality_issues(pg_conn, "LU_TEST_5", "MISSING", issues) == "MISSING"


def test_multiple_concurrent_issues_all_reach_ingestion_log(pg_conn):
    _make_tables(pg_conn)
    isin = "LU_TEST_6"
    issues = [
        ("FUNDCCY_NAME_KIID_MISMATCH", "WARN", "WARN", "fundccy mismatch"),
        ("ASSETCCY_NAME_KIID_MISMATCH", "WARN", "WARN", "assetccy mismatch"),
        ("INTER_NTC_CONTRADICTION", "WARN", "WARN", "ntc contradiction"),
    ]
    _finalize_data_quality_issues(pg_conn, isin, "OK", issues)

    rows = pg_conn.execute(
        "SELECT step, status, message FROM ingestion_log WHERE isin = %s ORDER BY id",
        (isin,),
    ).fetchall()
    assert len(rows) == 3
    steps = {r[0] for r in rows}
    assert steps == {
        "FUNDCCY_NAME_KIID_MISMATCH", "ASSETCCY_NAME_KIID_MISMATCH", "INTER_NTC_CONTRADICTION",
    }
    ntc_row = [r for r in rows if r[0] == "INTER_NTC_CONTRADICTION"][0]
    assert ntc_row[1] == "WARN"


def test_issues_persisted_to_fund_data_quality_issues_table(pg_conn):
    _make_tables(pg_conn)
    isin = "LU_TEST_7"
    issues = [
        ("HEDGCCY_NO_MISMATCH_INCONSISTENCY", "WARN", "WARN", "hedge inconsistente"),
        ("RC08_STRATEGY_INFERRED", "INFERRED", "INFO", "strategy inferida"),
    ]
    _finalize_data_quality_issues(pg_conn, isin, "OK", issues)

    rows = pg_conn.execute(
        "SELECT check_code, level, message FROM fund_data_quality_issues "
        "WHERE isin = %s ORDER BY check_code",
        (isin,),
    ).fetchall()
    assert rows == [
        ("HEDGCCY_NO_MISMATCH_INCONSISTENCY", "WARN", "hedge inconsistente"),
        ("RC08_STRATEGY_INFERRED", "INFERRED", "strategy inferida"),
    ]


def test_fund_data_quality_issues_rebuilt_each_cycle_not_accumulated(pg_conn):
    """Each cycle must fully replace an ISIN's rows (DELETE-then-INSERT), not accumulate them —
    also the first PG test in the repo to exercise shared/db.py's executemany() dialect-bridge
    helper via pipeline.py rather than a writer module."""
    _make_tables(pg_conn)
    isin = "LU_TEST_8"

    _finalize_data_quality_issues(
        pg_conn, isin, "OK",
        [("FUNDCCY_NAME_KIID_MISMATCH", "WARN", "WARN", "mismatch ciclo 1")],
    )
    rows = pg_conn.execute(
        "SELECT check_code FROM fund_data_quality_issues WHERE isin = %s", (isin,)
    ).fetchall()
    assert len(rows) == 1

    _finalize_data_quality_issues(pg_conn, isin, "OK", [])
    rows = pg_conn.execute(
        "SELECT check_code FROM fund_data_quality_issues WHERE isin = %s", (isin,)
    ).fetchall()
    assert rows == []


def test_finalize_does_not_affect_other_isins(pg_conn):
    _make_tables(pg_conn)
    _finalize_data_quality_issues(
        pg_conn, "LU_TEST_9A", "OK",
        [("FUNDCCY_NAME_KIID_MISMATCH", "WARN", "WARN", "mismatch A")],
    )
    _finalize_data_quality_issues(pg_conn, "LU_TEST_9B", "OK", [])

    rows_a = pg_conn.execute(
        "SELECT check_code FROM fund_data_quality_issues WHERE isin = %s", ("LU_TEST_9A",)
    ).fetchall()
    rows_b = pg_conn.execute(
        "SELECT check_code FROM fund_data_quality_issues WHERE isin = %s", ("LU_TEST_9B",)
    ).fetchall()
    assert len(rows_a) == 1
    assert len(rows_b) == 0
