-- =============================================================================
-- 35_control.sql — Control layer: pipeline state, audit tooling, migration bookkeeping,
--                   AND the automated maintenance apparatus (cluster/bloat/partition/disk).
-- =============================================================================
-- Depends on silver.fund_master and gold.* already existing (FKs below) — apply after
-- 10/20/30. Introspected directly from the live db/fondos.sqlite; renames per rename_map.yaml.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- control.fund_metric_state — 3,680 rows, per-fund calc fingerprint/state (P2 idempotency cache)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.fund_metric_state (
    isin                  varchar(12) NOT NULL,
    metric_version         text        NOT NULL DEFAULT 'v1',
    input_hash              text        NOT NULL,   -- SHA-1 hex, 40 chars
    calculated_at            date        NOT NULL,
    last_ols_quarter          text,
    last_ols_nav_count         integer,
    last_ols_calc_version      text,        -- CALC_VERSION of the last OLS run; NULL = stale (OLS gate is CALC_VERSION-aware)

    CONSTRAINT fund_metric_state_pkey PRIMARY KEY (isin, metric_version),
    CONSTRAINT fund_metric_state_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE
) WITH (fillfactor = 85);   -- rewritten every P2 cycle — HOT-eligible with the low secondary-index count here

-- -----------------------------------------------------------------------------
-- control.fund_metric_family_state — per-family calc fingerprint (FND-0236), used only while
-- shared.config.FAMILY_VERSIONING_ENABLED is on: one row per (fund, metric_version, family) so a change to one
-- metric family recomputes that family alone. Seeded lazily from fund_metric_state.input_hash (no backfill needed).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.fund_metric_family_state (
    isin           varchar(12) NOT NULL,
    metric_version text        NOT NULL DEFAULT 'v1',
    family         text        NOT NULL,
    input_hash     text        NOT NULL,   -- SHA-1 hex: data fingerprint + metric version + family token + the family's flags
    family_token   text        NOT NULL,   -- CALC_VERSION[.override] the family was last computed under
    calculated_at  date        NOT NULL,
    batch_id       text,
    CONSTRAINT fund_metric_family_state_pkey PRIMARY KEY (isin, metric_version, family),
    CONSTRAINT fund_metric_family_state_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE,
    CONSTRAINT fund_metric_family_state_family_ck CHECK (family IN
        ('risk','macro','momentum','capture','persistence','fx','regime','rolling','short'))
) WITH (fillfactor = 85);

-- -----------------------------------------------------------------------------
-- control.p2_pipeline_log — 575K rows, per-run traceability. Append-only.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.p2_pipeline_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin            text,       -- NOT varchar(12): confirmed against the live server 2026-09-19,
                                 -- 1/704,727 rows holds a comma-joined list of multiple ISINs
                                 -- (a batch-level SKIP log entry, step=NAV_LOAD, 116 chars) —
                                 -- a real logging convention (batch events log all affected
                                 -- ISINs together), not corruption like kiid_lifecycle's case.
                                 -- No FK on this column (it's a diagnostic log, not a domain
                                 -- reference), so widening it has no referential-integrity impact.
    step            text,       -- NAV_LOAD / DEFLATE / CALC_METRICS / WRITE / MV_REFRESH / CLUSTER_MAINT / ...
    status           text,       -- OK / WARN / ERROR / SKIP
    horizon           text,
    metric_version     text,
    message             text,
    created_at           timestamptz DEFAULT now(),
    batch_id             text
);

CREATE INDEX IF NOT EXISTS idx_p2log_isin ON control.p2_pipeline_log (isin);
CREATE INDEX IF NOT EXISTS idx_p2log_step ON control.p2_pipeline_log (step, created_at);
CREATE INDEX IF NOT EXISTS idx_p2log_batch ON control.p2_pipeline_log (batch_id) WHERE batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_p2log_created_brin ON control.p2_pipeline_log
  USING brin (created_at) WITH (pages_per_range = 32);   -- 100% correlated by construction (append-only)

-- -----------------------------------------------------------------------------
-- control.ingestion_log — 929K rows, P1 append-only log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.ingestion_log (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin          varchar(12),
    step           text,
    status          text,
    message          text,
    created_at        timestamptz
);

CREATE INDEX IF NOT EXISTS idx_log_isin ON control.ingestion_log (isin);
CREATE INDEX IF NOT EXISTS idx_log_status ON control.ingestion_log (status);
CREATE INDEX IF NOT EXISTS idx_log_step ON control.ingestion_log (step, created_at);
CREATE INDEX IF NOT EXISTS idx_log_created_brin ON control.ingestion_log
  USING brin (created_at) WITH (pages_per_range = 32);

-- Retention (§P2 — no partitioning for this table at current volume; quarterly chunked DELETE instead)
COMMENT ON TABLE control.ingestion_log IS
  'Append-only P1 log. Retention: quarterly DELETE WHERE created_at < now() - interval ''24 months'' '
  'in 100K-row chunks + VACUUM. Upgrade to PARTITION BY RANGE(created_at) only if this crosses ~50M rows.';

-- -----------------------------------------------------------------------------
-- control.nav_sources — 3,726 rows, Morningstar ms_id + date range + status
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.nav_sources (
    isin              varchar(12) PRIMARY KEY,
    source             text,        -- MORNINGSTAR / CNMV / NOT_FOUND
    source_id            text,        -- internal source ID, e.g. F0GBR04S23 in Morningstar
    first_nav_date         date,
    last_nav_date           date,
    nav_count                 integer,
    discovered_at             date,
    last_checked               date,
    status                     text CHECK (status IN ('OK','NOT_FOUND','ERROR')),
    data_status                 text DEFAULT 'OK'
        -- STALE_FROZEN added 2026-09-19: confirmed missing from the original CHECK list, found
        -- against the live server. Legitimate value, not a data-quality issue — added by the
        -- FIX-FROZEN-NAV project (nav_discovery.py auto-detects funds frozen >365 days, e.g. the
        -- Russia/EE sanctions cohort) after this table's original schema reference was current.
        -- The other 4 values (FORCE_REFRESH/RECALCULATE_MONTHLY/RECALCULATE_METRICS/PENDING) are
        -- kept even though only OK/STALE_FROZEN appear in today's snapshot — they're legitimate
        -- transient states in the documented nav_discovery state machine, not everything that
        -- happens to be live right now.
        -- INVALID_NAV added 2026-10-01 (FND-0164): set by run_pipeline._quarantine_invalid_nav() when
        -- validate_nav() rejects the series (>8x jumps); cleared back to OK once the series validates.
        CHECK (data_status IN ('OK','FORCE_REFRESH','RECALCULATE_MONTHLY','RECALCULATE_METRICS','PENDING','STALE_FROZEN','INVALID_NAV'))
);

CREATE INDEX IF NOT EXISTS idx_nav_sources_status ON control.nav_sources (status);
CREATE INDEX IF NOT EXISTS idx_nav_sources_source ON control.nav_sources (source);
CREATE INDEX IF NOT EXISTS idx_nav_sources_data_status ON control.nav_sources (data_status);

-- -----------------------------------------------------------------------------
-- control.benchmark_ms_checks — negative cache for proyecto1/src/loaders/benchmark_loader.py.
-- One row per ISIN for which Morningstar returned NO benchmark (or a rejected placeholder). The
-- loader's `--mode update` skips an ISIN until next_check_at, backing off per consecutive miss
-- (shared/config.py BENCH_NEGATIVE_BACKOFF_DAYS). PG-only, no SQLite source (like regime_history).
-- Deliberately NOT a sentinel row in silver.fund_benchmarks: pipeline.py prefers any MORNINGSTAR
-- row over a KIID row, so a "no benchmark" marker there would displace real KIID data.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.benchmark_ms_checks (
    isin              varchar(12) PRIMARY KEY,
    n_misses           integer     NOT NULL CHECK (n_misses >= 1),
    last_checked_at     timestamptz NOT NULL,
    next_check_at        timestamptz NOT NULL,

    CONSTRAINT benchmark_ms_checks_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bms_checks_next ON control.benchmark_ms_checks (next_check_at);

-- -----------------------------------------------------------------------------
-- control.audit_statistic / control.audit_finding — statistical-audit-engine outputs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.audit_statistic (
    stat_value      double precision,   -- NULL = not computed (never NaN)
    n                 integer,
    computed_at        timestamptz DEFAULT now(),
    run_id               text        NOT NULL,
    domain                text        NOT NULL CHECK (domain IN ('p2_metrics', 'cost_attributes')),
    population             text        NOT NULL,   -- 'GLOBAL' or a peer-segment label
    group_key               text        NOT NULL,   -- e.g. 'vol_ann|since_inception|0|v1'
    stat_name                 text        NOT NULL,   -- 'n_total' / 'p50' / 'skew' / 'zero_pct' / ...
    stat_text                   text,       -- status labels / non-numeric facts
    catalog_version               text,       -- content hash of the catalogs+tolerances; NULL = pre-versioning

    CONSTRAINT audit_statistic_pkey PRIMARY KEY (run_id, domain, population, group_key, stat_name)
);

CREATE INDEX IF NOT EXISTS idx_audit_statistic_run ON control.audit_statistic (run_id);
CREATE INDEX IF NOT EXISTS idx_audit_statistic_group ON control.audit_statistic (domain, group_key, stat_name);

CREATE TABLE IF NOT EXISTS control.audit_finding (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value                  double precision,
    reference_value          double precision,
    threshold                  double precision,
    distance                     double precision,
    detected_at                    timestamptz DEFAULT now(),
    run_id                          text        NOT NULL,
    domain                            text        NOT NULL CHECK (domain IN ('p2_metrics', 'cost_attributes')),
    block                              text        NOT NULL,   -- 'BLOCK1' .. 'BLOCK7'
    rule_id                             text        NOT NULL,
    rule_class                            text        NOT NULL
        CHECK (rule_class IN ('HARD_INVARIANT', 'PLAUSIBILITY', 'STATISTICAL_ANOMALY')),
    severity                               text        NOT NULL CHECK (severity IN ('INFO', 'WARN', 'ALARM')),
    group_key                                text        NOT NULL,
    isin                                       varchar(12),   -- NULL for population-level findings
    evidence                                     text,
    root_cause_candidate                           text,
    catalog_version                                  text,   -- content hash of the catalogs+tolerances; NULL = pre-versioning

    CONSTRAINT audit_finding_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_audit_finding_severity ON control.audit_finding (severity);
CREATE INDEX IF NOT EXISTS idx_audit_finding_isin ON control.audit_finding (isin);
CREATE INDEX IF NOT EXISTS idx_audit_finding_rule ON control.audit_finding (domain, rule_id);
CREATE INDEX IF NOT EXISTS idx_audit_finding_run ON control.audit_finding (run_id);

-- -----------------------------------------------------------------------------
-- control.audit_accepted_finding — accepted-residual baseline (FND-0234(e))
-- A (domain, rule, ISIN) violation the owner has decided to live with for now, tied to the AP that will fix it and
-- with a mandatory expiry. The audit engine downgrades a finding whose violating ISINs are ALL accepted (and still
-- reports them as INFO); an ISIN that is not accepted keeps the finding an ALARM, so only NEW violations alert.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.audit_accepted_finding (
    domain       text        NOT NULL,                  -- cost_attributes | p2_metrics (audit_finding.domain)
    rule_id      text        NOT NULL,
    isin         varchar(12) NOT NULL,
    ap_id        text        NOT NULL,                  -- the backlog ticket that owns the fix, e.g. FND-0034
    reason       text        NOT NULL,
    accepted_at  date        NOT NULL DEFAULT current_date,
    accepted_by  text,
    expires_at   date        NOT NULL,
    CONSTRAINT audit_accepted_finding_pkey PRIMARY KEY (domain, rule_id, isin),
    CONSTRAINT audit_accepted_finding_expiry_ck CHECK (expires_at > accepted_at)
);

-- -----------------------------------------------------------------------------
-- control.audit_finding_isin — the ISINs behind a group-level finding (FND-0234(d))
-- audit_finding keeps ONE row per invariant/group rule (isin NULL) -- "88/2809 rows violate" -- so which funds violated could
-- only be recovered by re-running the audit. One row per (run, rule, ISIN) here: triage without a 4-minute audit, violator
-- drift between runs (new / resolved / unchanged), and the input of the accepted-residual baseline.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.audit_finding_isin (
    run_id    text        NOT NULL,
    domain    text        NOT NULL,
    rule_id   text        NOT NULL,
    group_key text        NOT NULL,
    isin      varchar(12) NOT NULL,
    CONSTRAINT audit_finding_isin_pkey PRIMARY KEY (run_id, domain, rule_id, group_key, isin),
    CONSTRAINT audit_finding_isin_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- BEGIN cycle_telemetry (FND-0239) -- orchestrated-cycle telemetry: one row per cycle / step attempt, typed metrics with baselines
-- computed AT INGEST (no percentile work in views), flags linked to the backlog, the executive view v_cycle_exec.
-- Written best-effort by shared/cycle_telemetry.py (failure-isolated: a telemetry outage never changes a launcher RC).
-- Applied on the live DB only by the owner: scripts/ops/migrate_cycle_telemetry.py reads this block (single source of truth).
-- -----------------------------------------------------------------------------

-- One row per orchestrated cycle (P1_P2_Complete, P1_P2_P3, P2_P3_complete, P3_buildPortfolio).
CREATE TABLE IF NOT EXISTS control.cycle_run (
    cycle_id        text PRIMARY KEY,                  -- the launcher STAMP, YYYYMMDD_HHMMSS
    launcher        text        NOT NULL,
    parent_cycle_id text REFERENCES control.cycle_run (cycle_id),   -- --from N / --only-p3 lineage
    started_at      timestamptz NOT NULL,
    ended_at        timestamptz,
    status          text        NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING','OK','FAILED','ABORTED')),
    rc              integer,
    failed_step     text,
    resume_from     smallint,
    options         jsonb       NOT NULL DEFAULT '{}',
    calc_version    text,
    git_commit      text,
    restore_point   text,
    universe_active integer,
    regime          text,
    semaforo        text
);

-- The steps the executive view knows, with their duration ceilings as DATA (changing one is an UPDATE, not a deploy).
-- hard_max_s is active from the first cycle and stays a permanent backstop after warm-up: seeded at 2x the longest duration observed in
-- the 2026-10-04/05 logs (P2_CALC 16,158 s -> 32,400 s, P1_CLASSIFY 5,760 s -> 11,520 s); the others are generous placeholders.
CREATE TABLE IF NOT EXISTS control.cycle_step_def (
    step_code   text PRIMARY KEY,
    step_kind   text NOT NULL CHECK (step_kind IN ('PIPELINE','GATE','DIAGNOSTIC')),
    seq         smallint NOT NULL,
    description text NOT NULL,
    warn_ratio  numeric,                               -- duration / baseline median; NULL = never flagged on ratio
    alarm_ratio numeric,
    hard_max_s  double precision
);

-- One row per step attempt (a pipeline step, a gate or a diagnostic).
CREATE TABLE IF NOT EXISTS control.cycle_step (
    cycle_id    text        NOT NULL REFERENCES control.cycle_run (cycle_id) ON DELETE CASCADE,
    step_code   text        NOT NULL,
    attempt     smallint    NOT NULL DEFAULT 1,
    step_kind   text        NOT NULL CHECK (step_kind IN ('PIPELINE','GATE','DIAGNOSTIC')),
    seq         smallint,
    started_at  timestamptz NOT NULL,
    ended_at    timestamptz,
    rc          integer,
    dur_s       double precision,
    baseline_s  double precision,                      -- median dur_s of the previous <= 5 OK attempts of this step (NULL during warm-up)
    ratio       double precision,
    status      text CHECK (status IN ('RUNNING','OK','WARN','FAILED','SKIPPED')),
    warn_count  integer,
    error_count integer,
    batch_id    text,                                  -- joins control.p2_pipeline_log.batch_id for P2 steps
    log_path    text,
    CONSTRAINT cycle_step_pkey PRIMARY KEY (cycle_id, step_code, attempt)
);

-- The catalogue of scalar telemetry: meaning + thresholds as DATA.
CREATE TABLE IF NOT EXISTS control.cycle_metric_def (
    metric_code     text PRIMARY KEY,
    description     text NOT NULL,
    unit            text,
    direction       text CHECK (direction IN ('LOWER_BETTER','HIGHER_BETTER','NEUTRAL')),
    baseline_cycles smallint NOT NULL DEFAULT 5,
    warn_ratio      numeric,
    alarm_ratio     numeric,
    hard_min        double precision,                  -- absolute invariants only
    hard_max        double precision
);

-- Long-format scalar telemetry; baseline_value / ratio are written at ingest.
CREATE TABLE IF NOT EXISTS control.cycle_metric (
    cycle_id       text        NOT NULL REFERENCES control.cycle_run (cycle_id) ON DELETE CASCADE,
    step_code      text        NOT NULL,
    metric_code    text        NOT NULL,
    scope          text        NOT NULL DEFAULT '',    -- metric family / audit domain / nature / ''
    value_num      double precision,
    value_text     text,
    baseline_value double precision,
    ratio          double precision,
    recorded_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT cycle_metric_pkey PRIMARY KEY (cycle_id, step_code, metric_code, scope)
);

-- Audit runs attached to a cycle (the identity of the findings stays in control.audit_finding).
CREATE TABLE IF NOT EXISTS control.cycle_audit_run (
    cycle_id    text     NOT NULL REFERENCES control.cycle_run (cycle_id) ON DELETE CASCADE,
    domain      text     NOT NULL,                     -- p2_metrics | cost_attributes | benchmark
    phase       text     NOT NULL CHECK (phase IN ('pre','post')),
    run_id      text     NOT NULL,
    n_alarm     integer, n_warn integer, n_info integer,
    n_new       integer, n_resolved integer, n_unchanged integer,
    n_stagnant  integer,                               -- unchanged for >= 3 consecutive cycles
    CONSTRAINT cycle_audit_run_pkey PRIMARY KEY (cycle_id, domain, phase)
);

-- Flags raised at the end of a cycle by the rule catalogue; ap_id links to gestion.backlog (no FK: another database).
-- ap_status is read from the backlog AT WRITE TIME and has three distinct "no ticket" states so an outage of the backlog is never read as
-- "no ticket": a real status, NOT_FOUND (reachable, no such AP), LOOKUP_FAILED (exception / timeout; retried at the next ingest).
CREATE TABLE IF NOT EXISTS control.cycle_flag (
    cycle_id  text   NOT NULL REFERENCES control.cycle_run (cycle_id) ON DELETE CASCADE,
    flag_code text   NOT NULL,
    scope     text   NOT NULL DEFAULT '',
    severity  text   NOT NULL CHECK (severity IN ('INFO','WARN','HIGH')),
    detail    text,
    evidence  double precision,
    ap_id     text,                                    -- NULL = untracked (candidate for a new AP)
    ap_status text CHECK (ap_status IN ('OPEN','TODO','IN_PROGRESS','READY_FOR_DEPLOY','BLOCKED','DEFERRED','CLOSED','NOT_FOUND','LOOKUP_FAILED')),
    CONSTRAINT cycle_flag_pkey PRIMARY KEY (cycle_id, flag_code, scope)
);

-- Standing mapping flag -> AP (the zero-entropy policy): a flag with an unexpired ack inherits its ap_id.
CREATE TABLE IF NOT EXISTS control.cycle_flag_ack (
    flag_code  text NOT NULL,
    scope      text NOT NULL DEFAULT '',
    ap_id      text NOT NULL,
    note       text,
    expires_at date,
    CONSTRAINT cycle_flag_ack_pkey PRIMARY KEY (flag_code, scope)
);

CREATE INDEX IF NOT EXISTS idx_cycle_step_code   ON control.cycle_step (step_code, started_at);
CREATE INDEX IF NOT EXISTS idx_cycle_metric_code ON control.cycle_metric (metric_code, cycle_id);

-- Seeds (idempotent; thresholds are tuned with UPDATEs, never by editing this block).
INSERT INTO control.cycle_step_def (step_code, step_kind, seq, description, warn_ratio, alarm_ratio, hard_max_s) VALUES
    ('PREFLIGHT',     'GATE',       0, 'preflight: DB reachable, owner DSN, FRED key, disk',                 NULL, NULL,   600),
    ('AUDIT_BASE',    'DIAGNOSTIC', 1, 'baseline statistical audits (p2, costs) with --persist',             1.5,  3.0,   3600),
    ('BETA_SNAPSHOT', 'DIAGNOSTIC', 2, 'macro-beta snapshot before the cycle',                               1.5,  3.0,   3600),
    ('HARVEST',       'PIPELINE',   3, 'P1_harvestFunds: catalogue harvest + KIID delta',                    1.5,  3.0,   7200),
    ('P1_BENCH',      'PIPELINE',   4, 'PASO 1: benchmark refresh',                                          1.5,  3.0,   3600),
    ('P1_CLASSIFY',   'PIPELINE',   5, 'PASO 2: P1 nature-first classification',                             1.5,  3.0,  11520),
    ('P2_DISCOVER',   'PIPELINE',   6, 'PASO 3: macro + NAV discovery and load',                             1.5,  3.0,  14400),
    ('P2_CALC',       'PIPELINE',   7, 'PASO 4: P2 indicators (run_pipeline + export)',                      1.5,  3.0,  32400),
    ('AUDIT_FINAL',   'DIAGNOSTIC', 8, 'final statistical audits with drift against the baseline',           1.5,  3.0,   3600),
    ('BETA_COMPARE',  'DIAGNOSTIC', 9, 'macro-beta comparison against the snapshot',                         1.5,  3.0,   3600),
    ('P3_FRESHNESS',  'GATE',      10, 'P3 freshness verdict (same gate as P3)',                             NULL, NULL,   600),
    ('CYCLE_REPORT',  'DIAGNOSTIC',11, 'cycle report ([ATENCION] lines)',                                    1.5,  3.0,   1800),
    ('BETA_GATE',     'GATE',      12, 'beta gate of P1_P2_P3: blocking macro-beta comparison before P3',     NULL, NULL,   3600),
    ('P3_BUILD',      'PIPELINE',  13, 'P3 scoring + portfolio build',                                       1.5,  3.0,   7200),
    ('P3_REPORT',     'PIPELINE',  14, 'P3 monthly report',                                                  1.5,  3.0,   3600)
ON CONFLICT (step_code) DO NOTHING;

INSERT INTO control.cycle_metric_def (metric_code, description, unit, direction, warn_ratio, alarm_ratio) VALUES
    ('p2_processed',   'funds processed by the P2 run',                    'funds', 'NEUTRAL',      NULL, NULL),
    ('p2_skipped',     'funds skipped (cache hit) by the P2 run',          'funds', 'NEUTRAL',      NULL, NULL),
    ('p2_errors',      'funds that errored in the P2 run',                 'funds', 'LOWER_BETTER', 2.0,  5.0),
    ('p2_warnings',    'warnings of the P2 run',                           'count', 'LOWER_BETTER', 2.0,  5.0),
    ('p2_written_rows','metric rows written by the P2 run',                'rows',  'NEUTRAL',      NULL, NULL),
    ('p2_quarantined', 'metric rows quarantined by the P2 run',            'rows',  'LOWER_BETTER', 2.0,  5.0),
    ('ols_funds',      'funds that went through the macro OLS',            'funds', 'NEUTRAL',      NULL, NULL),
    ('cond_guard_funds','funds nulled by the condition-number guard',      'funds', 'LOWER_BETTER', 2.0,  5.0),
    ('betas_nulled',   'macro betas nulled by the VIF / guards',           'count', 'LOWER_BETTER', 2.0,  5.0),
    ('p2_elapsed_s',   'wall time of the P2 run',                          's',     'LOWER_BETTER', 1.5,  3.0),
    ('cache_hit_pct',  'share of funds skipped by the fingerprint cache',  'pct',   'NEUTRAL',      NULL, NULL),
    ('family_version_coverage_pct', 'share of rows of a metric family on the current algorithm_version', 'pct', 'HIGHER_BETTER', NULL, NULL),
    ('universe_active','active funds in the universe',                     'funds', 'NEUTRAL',      NULL, NULL),
    ('nav_stale_n',    'active funds whose newest NAV is stale (one predicate, FND-0233)', 'funds', 'LOWER_BETTER', 2.0, 5.0),
    ('dq_warn_n',      'open data-quality warnings of the cycle',          'count', 'LOWER_BETTER', 2.0,  5.0),
    ('alerts_alarm_n', 'rolling-signal ALARM alerts',                      'count', 'LOWER_BETTER', 2.0,  5.0),
    ('dist_drift_z',   'z-score of a key metric moment against its last runs', 'z',  'LOWER_BETTER', NULL, NULL),
    ('p3_scored',      'funds scored by P3',                               'funds', 'NEUTRAL',      NULL, NULL),
    ('p3_eligible',    'funds eligible after the P3 hard filters',         'funds', 'NEUTRAL',      NULL, NULL),
    ('portfolio_funds','funds in the built portfolio',                     'funds', 'NEUTRAL',      NULL, NULL)
ON CONFLICT (metric_code) DO NOTHING;

-- The executive view. Every source is pre-aggregated PER CYCLE before joining, so there is no steps x flags fan-out; baselines and ratios were
-- written at ingest, so there is no percentile / LATERAL work here.
CREATE OR REPLACE VIEW control.v_cycle_exec AS
WITH st AS (   -- last attempt of each step
    SELECT DISTINCT ON (cycle_id, step_code) cycle_id, step_code, dur_s, ratio, status
    FROM control.cycle_step ORDER BY cycle_id, step_code, attempt DESC),
stp AS (
    SELECT cycle_id,
           max(dur_s) FILTER (WHERE step_code = 'P1_CLASSIFY') / 60 AS p1_min,
           max(dur_s) FILTER (WHERE step_code = 'P2_DISCOVER') / 60 AS p2_load_min,
           max(dur_s) FILTER (WHERE step_code = 'P2_CALC')     / 60 AS p2_calc_min,
           max(dur_s) FILTER (WHERE step_code = 'P3_BUILD')    / 60 AS p3_min,
           max(ratio) AS worst_step_ratio,
           count(*) FILTER (WHERE status = 'FAILED') AS steps_failed
    FROM st GROUP BY cycle_id),
met AS (
    SELECT cycle_id,
           max(value_num) FILTER (WHERE metric_code = 'ols_funds')                    AS ols_funds,
           max(value_num) FILTER (WHERE metric_code = 'cache_hit_pct' AND scope = '') AS cache_hit_pct
    FROM control.cycle_metric GROUP BY cycle_id),
aud AS (
    SELECT cycle_id, sum(n_alarm) AS alarms_post, sum(n_stagnant) AS alarms_stagnant
    FROM control.cycle_audit_run WHERE phase = 'post' GROUP BY cycle_id),
fl AS (
    SELECT cycle_id,
           count(*) FILTER (WHERE severity = 'HIGH')                                                       AS flags_high,
           count(*) FILTER (WHERE severity <> 'INFO' AND (ap_id IS NULL OR ap_status IN ('CLOSED','NOT_FOUND'))) AS flags_orphan,
           count(*) FILTER (WHERE severity <> 'INFO' AND ap_status = 'LOOKUP_FAILED')                      AS flags_unverified,
           string_agg(flag_code, ',' ORDER BY flag_code) FILTER (WHERE severity = 'HIGH')                  AS high_flags
    FROM control.cycle_flag GROUP BY cycle_id)
SELECT r.cycle_id, r.launcher, r.started_at, r.status, r.failed_step,
       round((extract(epoch FROM r.ended_at - r.started_at) / 3600)::numeric, 2) AS total_h,
       stp.p1_min, stp.p2_load_min, stp.p2_calc_min, stp.p3_min, stp.worst_step_ratio, COALESCE(stp.steps_failed, 0) AS steps_failed,
       met.ols_funds, met.cache_hit_pct, aud.alarms_post, aud.alarms_stagnant,
       COALESCE(fl.flags_high, 0) AS flags_high, COALESCE(fl.flags_orphan, 0) AS flags_orphan,   -- orphan => candidate for a new AP
       COALESCE(fl.flags_unverified, 0) AS flags_unverified,                                      -- backlog lookup failed; retried at ingest
       fl.high_flags, r.regime, r.semaforo
FROM control.cycle_run r
LEFT JOIN stp USING (cycle_id) LEFT JOIN met USING (cycle_id)
LEFT JOIN aud USING (cycle_id) LEFT JOIN fl USING (cycle_id);
-- END cycle_telemetry

-- =============================================================================
-- Migration bookkeeping (new in PG — no SQLite analog)
-- =============================================================================

-- One row per completed migration/reconciliation-gate pass (§Verification "On green").
CREATE TABLE IF NOT EXISTS control.migration_state (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migrated_at         timestamptz NOT NULL DEFAULT now(),
    pg_version           text        NOT NULL,
    source_sqlite_path     text        NOT NULL,
    source_sqlite_size_bytes bigint    NOT NULL,
    source_sqlite_sha256      text        NOT NULL,
    gate_results               jsonb       NOT NULL,   -- per-check pass/fail from §Verification
    notes                        text
);

-- Seed-loader restart bookkeeping (§P3 "Restart semantics"). Table/partition-granularity resume —
-- a crash mid-COPY resumes at the failed unit, not a full re-run of the 55-90 min load. Dropped or
-- archived once the reconciliation gate passes.
CREATE TABLE IF NOT EXISTS control.seed_progress (
    target_table    text PRIMARY KEY,   -- e.g. 'gold.fmts_p_sharpe', 'bronze.fund_nav_daily'
    status           text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done')),
    completed_at       timestamptz
);

-- Orphan quarantine tables (§P3 "Orphan pre-scan" + Reconciliation gate check (d)). One per
-- FK-bearing target whose SQLite-side orphan set is identified BEFORE any COPY runs, so orphans
-- are routed here in the same pass instead of being discovered at VALIDATE CONSTRAINT time after
-- a 40-minute load. `LIKE ... INCLUDING ALL` never copies FOREIGN KEY constraints (PG semantics),
-- so no explicit "drop the FK" step is needed.
--
-- gold.fund_metric_timeseries is the KNOWN risk (its FK was lost in the live v29 SQLite rebuild —
-- see 30_gold.sql comment); the other eight are covered on the same principle, since the pre-scan
-- is cheap and the alternative (discovering an orphan there instead, unquarantined) is not.
DO $$
DECLARE
  targets text[][] := ARRAY[
    ARRAY['gold',   'fund_metric_timeseries'],
    ARRAY['gold',   'fund_metrics'],
    ARRAY['gold',   'fund_metric_alerts'],
    ARRAY['gold',   'fund_scores'],
    ARRAY['gold',   'portfolio_weights'],
    ARRAY['bronze', 'fund_nav_daily'],
    ARRAY['bronze', 'fund_nav_monthly'],
    ARRAY['control','fund_metric_state'],
    ARRAY['control','audit_finding']
  ];
  i int;
BEGIN
  FOR i IN 1 .. array_length(targets, 1) LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS control.quarantine_%s_orphans (LIKE %I.%I INCLUDING ALL)',
      targets[i][2], targets[i][1], targets[i][2]
    );
  END LOOP;
END $$;

COMMENT ON TABLE control.quarantine_fund_metric_timeseries_orphans IS
  'Rows from the SQLite source whose isin has no matching silver.fund_master row, routed here '
  'during the seed COPY (§P3 step 3/5) instead of reaching the FK-bearing target. Gate check (d) '
  'requires this count to equal the SQLite-side pre-scan count exactly.';


-- =============================================================================
-- Automated maintenance apparatus (§P2 "Clustering", "Bloat monitoring")
-- One named entry point (control.run_monthly_maintenance, defined in 40_matviews.sql once
-- refresh_gold_matviews() also exists) wraps everything below plus the disk-headroom pre-flight.
-- =============================================================================

-- --- Cluster health: measured and self-triggering, not a calendar reminder ---
CREATE OR REPLACE VIEW control.v_cluster_health AS
SELECT schemaname, tablename, correlation,
       correlation < 0.90 AS needs_cluster
FROM   pg_stats
WHERE  attname = 'isin'
  AND ( (schemaname, tablename) IN (('bronze','fund_nav_daily'), ('gold','fund_metrics'))
        OR tablename LIKE 'fmts_p_%' );

CREATE OR REPLACE FUNCTION control.maintain_clusters(p_threshold numeric DEFAULT 0.90)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  r record;
  v_pkey name;
  t0 timestamptz;
BEGIN
  FOR r IN SELECT schemaname, tablename FROM control.v_cluster_health WHERE needs_cluster LOOP
    t0 := clock_timestamp();
    -- CLUSTER with no USING clause requires the table to have been clustered before
    -- (relies on indisclustered from a prior run); on a never-clustered table it raises
    -- UndefinedObject ("no previously clustered index"). Look up the PK index explicitly.
    SELECT ic.relname INTO v_pkey
    FROM   pg_index i
    JOIN   pg_class ic ON ic.oid = i.indexrelid
    JOIN   pg_class tc ON tc.oid = i.indrelid
    JOIN   pg_namespace n ON n.oid = tc.relnamespace
    WHERE  n.nspname = r.schemaname AND tc.relname = r.tablename AND i.indisprimary;
    EXECUTE format('CLUSTER %I.%I USING %I', r.schemaname, r.tablename, v_pkey);
    EXECUTE format('ANALYZE %I.%I', r.schemaname, r.tablename);
    INSERT INTO control.p2_pipeline_log (step, status, message)
      VALUES ('CLUSTER_MAINT', 'OK',
              format('%s.%s reclustered in %s', r.schemaname, r.tablename,
                     clock_timestamp() - t0));
  END LOOP;
  IF NOT FOUND THEN
    INSERT INTO control.p2_pipeline_log (step, status, message)
      VALUES ('CLUSTER_MAINT', 'SKIP', 'nothing below correlation threshold');
  END IF;
END $$;

-- --- Bloat: measurable via pgstattuple; small tables auto-remediate, big tables alert only ---
CREATE OR REPLACE VIEW control.v_bloat_health AS
SELECT schemaname, tablename,
       pg_table_size(format('%I.%I', schemaname, tablename)::regclass) AS table_size_bytes,
       (pgstattuple(format('%I.%I', schemaname, tablename)::regclass)).dead_tuple_percent,
       (pgstattuple(format('%I.%I', schemaname, tablename)::regclass)).dead_tuple_percent > 15
         AS needs_attention
FROM   pg_tables
WHERE  schemaname IN ('bronze','silver','gold','control')
  -- exclude the two big tables from the routine (monthly) pass — a pgstattuple full scan of them
  -- is itself an IO event worth budgeting quarterly, not a free monthly check (§P2 index plan)
  AND NOT (schemaname = 'gold' AND tablename LIKE 'fmts_p_%')
  AND NOT (schemaname = 'bronze' AND tablename = 'fund_nav_daily');

CREATE OR REPLACE FUNCTION control.maintain_bloat(p_threshold numeric DEFAULT 15)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT schemaname, tablename, table_size_bytes
           FROM control.v_bloat_health WHERE needs_attention LOOP
    IF r.table_size_bytes < 100 * 1024 * 1024 THEN   -- ~ under 100K-row-class tables
      EXECUTE format('VACUUM (FULL) %I.%I', r.schemaname, r.tablename);
      INSERT INTO control.p2_pipeline_log (step, status, message)
        VALUES ('BLOAT_AUTOVACUUM_FULL', 'OK', format('%s.%s', r.schemaname, r.tablename));
    ELSE
      INSERT INTO control.p2_pipeline_log (step, status, message)
        VALUES ('BLOAT_ALERT', 'WARN',
                format('%s.%s dead_tuple_percent > %s — see maintain_clusters()',
                       r.schemaname, r.tablename, p_threshold));
    END IF;
  END LOOP;
END $$;

-- --- DEFAULT partition: detect accumulation (CI test is the primary gate — see §5a in the plan;
-- this view is the RUNTIME backstop for a metric appearing in data without a matching code change) ---
CREATE OR REPLACE VIEW control.v_default_partition_metrics AS
SELECT metric, count(*) AS n_rows
FROM   gold.fmts_p_default
GROUP  BY metric;

-- --- huge_pages: PG-side leg of the two-leg monthly check (the host-side /proc/meminfo leg runs
-- from outside the DB — see the OS-level disk/hugepages check script referenced in §P1/§P2) ---
CREATE OR REPLACE FUNCTION control.check_hugepages() RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_status text;
BEGIN
  SELECT setting INTO v_status FROM pg_settings WHERE name = 'huge_pages_status';
  IF v_status IS DISTINCT FROM 'on' THEN
    INSERT INTO control.p2_pipeline_log (step, status, message)
      VALUES ('HUGEPAGES_DRIFT', 'WARN', format('huge_pages_status=%s', v_status));
  END IF;
END $$;

-- --- Disk headroom pre-flight (§P2 "Disk headroom" / §P3 seed-time equivalent). The gating check
-- itself runs from the wrapping shell/Python script (host `df` isn't visible to SQL) — this
-- function is the logging contract that script writes into, so CLUSTER_MAINT/BLOAT_ALERT and a
-- skipped-for-space event land in the same place.
CREATE OR REPLACE FUNCTION control.log_disk_headroom_skip(
  p_operation text, p_required_bytes bigint, p_available_bytes bigint
) RETURNS void LANGUAGE sql AS $$
  INSERT INTO control.p2_pipeline_log (step, status, message)
  VALUES ('DISK_HEADROOM_SKIP', 'WARN',
          format('%s skipped: required=%s available=%s',
                 p_operation, p_required_bytes, p_available_bytes));
$$;

-- BEGIN p3_gate_bypass (FND-0244 follow-up) -- audit trail of a P3 `--allow-stale` override
-- Owner migration: scripts/ops/migrate_audit_finding_p3_gate.py (dry run by default). Idempotent. Nothing depends on it:
-- shared/gate_bypass.py feature-detects the CHECK below and otherwise records the bypass in control.ingestion_log only.
DO $$
DECLARE c text;
BEGIN
  FOR c IN SELECT conname FROM pg_constraint
            WHERE conrelid = 'control.audit_finding'::regclass AND contype = 'c'
              AND pg_get_constraintdef(oid) ILIKE '%domain%' AND pg_get_constraintdef(oid) NOT ILIKE '%p3_gate%'
  LOOP
    EXECUTE format('ALTER TABLE control.audit_finding DROP CONSTRAINT %I', c);
  END LOOP;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'control.audit_finding'::regclass AND contype = 'c'
                  AND pg_get_constraintdef(oid) ILIKE '%p3_gate%') THEN
    ALTER TABLE control.audit_finding ADD CONSTRAINT audit_finding_domain_check
      CHECK (domain IN ('p2_metrics', 'cost_attributes', 'p3_gate'));
  END IF;
END $$;

-- One reading surface whatever the DDL state: the ingestion_log rows always, the audit_finding rows once the CHECK admits them.
CREATE OR REPLACE VIEW control.v_p3_gate_bypass AS
  SELECT 'ingestion_log'::text AS source, created_at AS event_ts, isin, message AS detail
    FROM control.ingestion_log WHERE step = 'P3_STALE_BYPASS'
  UNION ALL
  SELECT 'audit_finding'::text, detected_at, isin, evidence
    FROM control.audit_finding WHERE domain = 'p3_gate';
-- END p3_gate_bypass
