-- =============================================================================
-- 35_control.sql — Control layer: pipeline state, audit tooling, migration bookkeeping,
--                   AND the automated maintenance apparatus (cluster/bloat/partition/disk).
-- =============================================================================
-- Depends on silver.fund_master and gold.* already existing (FKs below) — apply after
-- 10/20/30. Introspected directly from the live db/fondos.sqlite; renames per rename_map.yaml.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- control.fund_metric_state — 3,680 rows, per-fund calc fingerprint/state (P2 idempotency cache)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.fund_metric_state (
    isin                  varchar(12) NOT NULL,
    metric_version         text        NOT NULL DEFAULT 'v1',
    input_hash              text        NOT NULL,   -- SHA-1 hex, 40 chars
    calculated_at            date        NOT NULL,
    last_ols_quarter          text,
    last_ols_nav_count         integer,

    CONSTRAINT fund_metric_state_pkey PRIMARY KEY (isin, metric_version),
    CONSTRAINT fund_metric_state_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE
) WITH (fillfactor = 85);   -- rewritten every P2 cycle — HOT-eligible with the low secondary-index count here

-- -----------------------------------------------------------------------------
-- control.p2_pipeline_log — 575K rows, per-run traceability. Append-only.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.p2_pipeline_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin            text,       -- NOT varchar(12): confirmed against the live server 2026-09-19,
                                 -- 1/704,727 rows holds a comma-joined list of multiple ISINs
                                 -- (a batch-level SKIP log entry, step=NAV_LOAD, 116 chars) —
                                 -- a real logging convention (batch events log all affected
                                 -- ISINs together), not corruption like kiid_lifecycle's case.
                                 -- No FK on this column (it's a diagnostic log, not a domain
                                 -- reference), so widening it has no referential-integrity impact.
    step            text,       -- NAV_LOAD / DEFLATE / CALC_METRICS / WRITE / MV_REFRESH / CLUSTER_MAINT / ...
    status           text,       -- OK / WARN / ERROR / SKIP
    horizon           text,
    metric_version     text,
    message             text,
    created_at           timestamptz DEFAULT now(),
    batch_id             text
);

CREATE INDEX IF NOT EXISTS idx_p2log_isin ON control.p2_pipeline_log (isin);
CREATE INDEX IF NOT EXISTS idx_p2log_step ON control.p2_pipeline_log (step, created_at);
CREATE INDEX IF NOT EXISTS idx_p2log_batch ON control.p2_pipeline_log (batch_id) WHERE batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_p2log_created_brin ON control.p2_pipeline_log
  USING brin (created_at) WITH (pages_per_range = 32);   -- 100% correlated by construction (append-only)

-- -----------------------------------------------------------------------------
-- control.ingestion_log — 929K rows, P1 append-only log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.ingestion_log (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin          varchar(12),
    step           text,
    status          text,
    message          text,
    created_at        timestamptz
);

CREATE INDEX IF NOT EXISTS idx_log_isin ON control.ingestion_log (isin);
CREATE INDEX IF NOT EXISTS idx_log_status ON control.ingestion_log (status);
CREATE INDEX IF NOT EXISTS idx_log_step ON control.ingestion_log (step, created_at);
CREATE INDEX IF NOT EXISTS idx_log_created_brin ON control.ingestion_log
  USING brin (created_at) WITH (pages_per_range = 32);

-- Retention (§P2 — no partitioning for this table at current volume; quarterly chunked DELETE instead)
COMMENT ON TABLE control.ingestion_log IS
  'Append-only P1 log. Retention: quarterly DELETE WHERE created_at < now() - interval ''24 months'' '
  'in 100K-row chunks + VACUUM. Upgrade to PARTITION BY RANGE(created_at) only if this crosses ~50M rows.';

-- -----------------------------------------------------------------------------
-- control.nav_sources — 3,726 rows, Morningstar ms_id + date range + status
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.nav_sources (
    isin              varchar(12) PRIMARY KEY,
    source             text,        -- MORNINGSTAR / CNMV / NOT_FOUND
    source_id            text,        -- internal source ID, e.g. F0GBR04S23 in Morningstar
    first_nav_date         date,
    last_nav_date           date,
    nav_count                 integer,
    discovered_at             date,
    last_checked               date,
    status                     text CHECK (status IN ('OK','NOT_FOUND','ERROR')),
    data_status                 text DEFAULT 'OK'
        -- STALE_FROZEN added 2026-09-19: confirmed missing from the original CHECK list, found
        -- against the live server. Legitimate value, not a data-quality issue — added by the
        -- FIX-FROZEN-NAV project (nav_discovery.py auto-detects funds frozen >365 days, e.g. the
        -- Russia/EE sanctions cohort) after this table's original schema reference was current.
        -- The other 4 values (FORCE_REFRESH/RECALCULATE_MONTHLY/RECALCULATE_METRICS/PENDING) are
        -- kept even though only OK/STALE_FROZEN appear in today's snapshot — they're legitimate
        -- transient states in the documented nav_discovery state machine, not everything that
        -- happens to be live right now.
        CHECK (data_status IN ('OK','FORCE_REFRESH','RECALCULATE_MONTHLY','RECALCULATE_METRICS','PENDING','STALE_FROZEN'))
);

CREATE INDEX IF NOT EXISTS idx_nav_sources_status ON control.nav_sources (status);
CREATE INDEX IF NOT EXISTS idx_nav_sources_source ON control.nav_sources (source);
CREATE INDEX IF NOT EXISTS idx_nav_sources_data_status ON control.nav_sources (data_status);

-- -----------------------------------------------------------------------------
-- control.benchmark_ms_checks — negative cache for proyecto1/src/loaders/benchmark_loader.py.
-- One row per ISIN for which Morningstar returned NO benchmark (or a rejected placeholder). The
-- loader's `--mode update` skips an ISIN until next_check_at, backing off per consecutive miss
-- (shared/config.py BENCH_NEGATIVE_BACKOFF_DAYS). PG-only, no SQLite source (like regime_history).
-- Deliberately NOT a sentinel row in silver.fund_benchmarks: pipeline.py prefers any MORNINGSTAR
-- row over a KIID row, so a "no benchmark" marker there would displace real KIID data.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.benchmark_ms_checks (
    isin              varchar(12) PRIMARY KEY,
    n_misses           integer     NOT NULL CHECK (n_misses >= 1),
    last_checked_at     timestamptz NOT NULL,
    next_check_at        timestamptz NOT NULL,

    CONSTRAINT benchmark_ms_checks_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bms_checks_next ON control.benchmark_ms_checks (next_check_at);

-- -----------------------------------------------------------------------------
-- control.audit_statistic / control.audit_finding — statistical-audit-engine outputs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.audit_statistic (
    stat_value      double precision,   -- NULL = not computed (never NaN)
    n                 integer,
    computed_at        timestamptz DEFAULT now(),
    run_id               text        NOT NULL,
    domain                text        NOT NULL CHECK (domain IN ('p2_metrics', 'cost_attributes')),
    population             text        NOT NULL,   -- 'GLOBAL' or a peer-segment label
    group_key               text        NOT NULL,   -- e.g. 'vol_ann|since_inception|0|v1'
    stat_name                 text        NOT NULL,   -- 'n_total' / 'p50' / 'skew' / 'zero_pct' / ...
    stat_text                   text,       -- status labels / non-numeric facts
    catalog_version               text,       -- content hash of the catalogs+tolerances; NULL = pre-versioning

    CONSTRAINT audit_statistic_pkey PRIMARY KEY (run_id, domain, population, group_key, stat_name)
);

CREATE INDEX IF NOT EXISTS idx_audit_statistic_run ON control.audit_statistic (run_id);
CREATE INDEX IF NOT EXISTS idx_audit_statistic_group ON control.audit_statistic (domain, group_key, stat_name);

CREATE TABLE IF NOT EXISTS control.audit_finding (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value                  double precision,
    reference_value          double precision,
    threshold                  double precision,
    distance                     double precision,
    detected_at                    timestamptz DEFAULT now(),
    run_id                          text        NOT NULL,
    domain                            text        NOT NULL CHECK (domain IN ('p2_metrics', 'cost_attributes')),
    block                              text        NOT NULL,   -- 'BLOCK1' .. 'BLOCK7'
    rule_id                             text        NOT NULL,
    rule_class                            text        NOT NULL
        CHECK (rule_class IN ('HARD_INVARIANT', 'PLAUSIBILITY', 'STATISTICAL_ANOMALY')),
    severity                               text        NOT NULL CHECK (severity IN ('INFO', 'WARN', 'ALARM')),
    group_key                                text        NOT NULL,
    isin                                       varchar(12),   -- NULL for population-level findings
    evidence                                     text,
    root_cause_candidate                           text,
    catalog_version                                  text,   -- content hash of the catalogs+tolerances; NULL = pre-versioning

    CONSTRAINT audit_finding_isin_fk FOREIGN KEY (isin) REFERENCES silver.fund_master (isin) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_audit_finding_severity ON control.audit_finding (severity);
CREATE INDEX IF NOT EXISTS idx_audit_finding_isin ON control.audit_finding (isin);
CREATE INDEX IF NOT EXISTS idx_audit_finding_rule ON control.audit_finding (domain, rule_id);
CREATE INDEX IF NOT EXISTS idx_audit_finding_run ON control.audit_finding (run_id);


-- =============================================================================
-- Migration bookkeeping (new in PG — no SQLite analog)
-- =============================================================================

-- One row per completed migration/reconciliation-gate pass (§Verification "On green").
CREATE TABLE IF NOT EXISTS control.migration_state (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migrated_at         timestamptz NOT NULL DEFAULT now(),
    pg_version           text        NOT NULL,
    source_sqlite_path     text        NOT NULL,
    source_sqlite_size_bytes bigint    NOT NULL,
    source_sqlite_sha256      text        NOT NULL,
    gate_results               jsonb       NOT NULL,   -- per-check pass/fail from §Verification
    notes                        text
);

-- Seed-loader restart bookkeeping (§P3 "Restart semantics"). Table/partition-granularity resume —
-- a crash mid-COPY resumes at the failed unit, not a full re-run of the 55-90 min load. Dropped or
-- archived once the reconciliation gate passes.
CREATE TABLE IF NOT EXISTS control.seed_progress (
    target_table    text PRIMARY KEY,   -- e.g. 'gold.fmts_p_sharpe', 'bronze.fund_nav_daily'
    status           text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done')),
    completed_at       timestamptz
);

-- Orphan quarantine tables (§P3 "Orphan pre-scan" + Reconciliation gate check (d)). One per
-- FK-bearing target whose SQLite-side orphan set is identified BEFORE any COPY runs, so orphans
-- are routed here in the same pass instead of being discovered at VALIDATE CONSTRAINT time after
-- a 40-minute load. `LIKE ... INCLUDING ALL` never copies FOREIGN KEY constraints (PG semantics),
-- so no explicit "drop the FK" step is needed.
--
-- gold.fund_metric_timeseries is the KNOWN risk (its FK was lost in the live v29 SQLite rebuild —
-- see 30_gold.sql comment); the other eight are covered on the same principle, since the pre-scan
-- is cheap and the alternative (discovering an orphan there instead, unquarantined) is not.
DO $$
DECLARE
  targets text[][] := ARRAY[
    ARRAY['gold',   'fund_metric_timeseries'],
    ARRAY['gold',   'fund_metrics'],
    ARRAY['gold',   'fund_metric_alerts'],
    ARRAY['gold',   'fund_scores'],
    ARRAY['gold',   'portfolio_weights'],
    ARRAY['bronze', 'fund_nav_daily'],
    ARRAY['bronze', 'fund_nav_monthly'],
    ARRAY['control','fund_metric_state'],
    ARRAY['control','audit_finding']
  ];
  i int;
BEGIN
  FOR i IN 1 .. array_length(targets, 1) LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS control.quarantine_%s_orphans (LIKE %I.%I INCLUDING ALL)',
      targets[i][2], targets[i][1], targets[i][2]
    );
  END LOOP;
END $$;

COMMENT ON TABLE control.quarantine_fund_metric_timeseries_orphans IS
  'Rows from the SQLite source whose isin has no matching silver.fund_master row, routed here '
  'during the seed COPY (§P3 step 3/5) instead of reaching the FK-bearing target. Gate check (d) '
  'requires this count to equal the SQLite-side pre-scan count exactly.';


-- =============================================================================
-- Automated maintenance apparatus (§P2 "Clustering", "Bloat monitoring")
-- One named entry point (control.run_monthly_maintenance, defined in 40_matviews.sql once
-- refresh_gold_matviews() also exists) wraps everything below plus the disk-headroom pre-flight.
-- =============================================================================

-- --- Cluster health: measured and self-triggering, not a calendar reminder ---
CREATE OR REPLACE VIEW control.v_cluster_health AS
SELECT schemaname, tablename, correlation,
       correlation < 0.90 AS needs_cluster
FROM   pg_stats
WHERE  attname = 'isin'
  AND ( (schemaname, tablename) IN (('bronze','fund_nav_daily'), ('gold','fund_metrics'))
        OR tablename LIKE 'fmts_p_%' );

CREATE OR REPLACE FUNCTION control.maintain_clusters(p_threshold numeric DEFAULT 0.90)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  r record;
  t0 timestamptz;
BEGIN
  FOR r IN SELECT schemaname, tablename FROM control.v_cluster_health WHERE needs_cluster LOOP
    t0 := clock_timestamp();
    EXECUTE format('CLUSTER %I.%I', r.schemaname, r.tablename);
    EXECUTE format('ANALYZE %I.%I', r.schemaname, r.tablename);
    INSERT INTO control.p2_pipeline_log (step, status, message)
      VALUES ('CLUSTER_MAINT', 'OK',
              format('%s.%s reclustered in %s', r.schemaname, r.tablename,
                     clock_timestamp() - t0));
  END LOOP;
  IF NOT FOUND THEN
    INSERT INTO control.p2_pipeline_log (step, status, message)
      VALUES ('CLUSTER_MAINT', 'SKIP', 'nothing below correlation threshold');
  END IF;
END $$;

-- --- Bloat: measurable via pgstattuple; small tables auto-remediate, big tables alert only ---
CREATE OR REPLACE VIEW control.v_bloat_health AS
SELECT schemaname, tablename,
       pg_table_size(format('%I.%I', schemaname, tablename)::regclass) AS table_size_bytes,
       (pgstattuple(format('%I.%I', schemaname, tablename)::regclass)).dead_tuple_percent,
       (pgstattuple(format('%I.%I', schemaname, tablename)::regclass)).dead_tuple_percent > 15
         AS needs_attention
FROM   pg_tables
WHERE  schemaname IN ('bronze','silver','gold','control')
  -- exclude the two big tables from the routine (monthly) pass — a pgstattuple full scan of them
  -- is itself an IO event worth budgeting quarterly, not a free monthly check (§P2 index plan)
  AND NOT (schemaname = 'gold' AND tablename LIKE 'fmts_p_%')
  AND NOT (schemaname = 'bronze' AND tablename = 'fund_nav_daily');

CREATE OR REPLACE FUNCTION control.maintain_bloat(p_threshold numeric DEFAULT 15)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT schemaname, tablename, table_size_bytes
           FROM control.v_bloat_health WHERE needs_attention LOOP
    IF r.table_size_bytes < 100 * 1024 * 1024 THEN   -- ~ under 100K-row-class tables
      EXECUTE format('VACUUM (FULL) %I.%I', r.schemaname, r.tablename);
      INSERT INTO control.p2_pipeline_log (step, status, message)
        VALUES ('BLOAT_AUTOVACUUM_FULL', 'OK', format('%s.%s', r.schemaname, r.tablename));
    ELSE
      INSERT INTO control.p2_pipeline_log (step, status, message)
        VALUES ('BLOAT_ALERT', 'WARN',
                format('%s.%s dead_tuple_percent > %s — see maintain_clusters()',
                       r.schemaname, r.tablename, p_threshold));
    END IF;
  END LOOP;
END $$;

-- --- DEFAULT partition: detect accumulation (CI test is the primary gate — see §5a in the plan;
-- this view is the RUNTIME backstop for a metric appearing in data without a matching code change) ---
CREATE OR REPLACE VIEW control.v_default_partition_metrics AS
SELECT metric, count(*) AS n_rows
FROM   gold.fmts_p_default
GROUP  BY metric;

-- --- huge_pages: PG-side leg of the two-leg monthly check (the host-side /proc/meminfo leg runs
-- from outside the DB — see the OS-level disk/hugepages check script referenced in §P1/§P2) ---
CREATE OR REPLACE FUNCTION control.check_hugepages() RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_status text;
BEGIN
  SELECT setting INTO v_status FROM pg_settings WHERE name = 'huge_pages_status';
  IF v_status IS DISTINCT FROM 'on' THEN
    INSERT INTO control.p2_pipeline_log (step, status, message)
      VALUES ('HUGEPAGES_DRIFT', 'WARN', format('huge_pages_status=%s', v_status));
  END IF;
END $$;

-- --- Disk headroom pre-flight (§P2 "Disk headroom" / §P3 seed-time equivalent). The gating check
-- itself runs from the wrapping shell/Python script (host `df` isn't visible to SQL) — this
-- function is the logging contract that script writes into, so CLUSTER_MAINT/BLOAT_ALERT and a
-- skipped-for-space event land in the same place.
CREATE OR REPLACE FUNCTION control.log_disk_headroom_skip(
  p_operation text, p_required_bytes bigint, p_available_bytes bigint
) RETURNS void LANGUAGE sql AS $$
  INSERT INTO control.p2_pipeline_log (step, status, message)
  VALUES ('DISK_HEADROOM_SKIP', 'WARN',
          format('%s skipped: required=%s available=%s',
                 p_operation, p_required_bytes, p_available_bytes));
$$;
