"""
Generate db/pg_bi_compat/bi_compat.sql — a TEMPORARY read-only compatibility schema for Superset.

The legacy BI store (:5433) carries SQLite's column names (fund_master."ISIN", ..., and "window" on
the two rolling-metric tables). The primary Postgres uses lower_snake names (window -> window_label).
Repointing Superset at the primary database would therefore break every dataset/chart that names an
old column. `bi_compat.<table>` exposes the primary tables under their LEGACY table and column
names, so only the dataset's connection/schema changes, not its columns.

Generated from db/pg/rename_map.yaml (the source of truth for old->new), never hand-edited:
    python scripts/mig/gen_bi_compat.py            # rewrite the SQL file
    python scripts/mig/gen_bi_compat.py --check    # exit 1 if the committed file is stale

Applied by hand at cutover (deliberately NOT in db/pg/, whose files run automatically at initdb and
are listed in CI). Drop the schema once the datasets are migrated to the new names.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
RENAME_MAP = REPO_ROOT / "db" / "pg" / "rename_map.yaml"
OUT_FILE = REPO_ROOT / "db" / "pg_bi_compat" / "bi_compat.sql"

# The three datasets registered in Superset (AGENTS.md, P4 BI mirror).
BI_TABLES = ("fund_master", "fund_metric_timeseries", "fund_metric_alerts")


def _q(ident: str) -> str:
    return '"' + ident.replace('"', '""') + '"'


def render(rename_map: dict) -> str:
    layer_of = {t: layer for layer, tables in rename_map["schema_layer"].items() for t in tables}
    out = [
        "-- GENERATED by scripts/mig/gen_bi_compat.py from db/pg/rename_map.yaml — do not edit by hand.",
        "-- TEMPORARY read-only bridge so Superset datasets keep their legacy table/column names",
        "-- (\"ISIN\", \"window\", ...) after repointing at the primary Postgres. Apply once, as the",
        "-- schema owner, at cutover; DROP SCHEMA bi_compat CASCADE once datasets use the new names.",
        "",
        "CREATE SCHEMA IF NOT EXISTS bi_compat;",
        "GRANT USAGE ON SCHEMA bi_compat TO superset_ro;",
        "",
    ]
    for table in BI_TABLES:
        cols = rename_map["columns"][table]
        select = ",\n".join(f"       {_q(new)} AS {_q(old)}" for old, new in cols.items())
        out += [
            f"CREATE OR REPLACE VIEW bi_compat.{table} AS",
            "SELECT",
            select,
            f"FROM   {layer_of[table]}.{table};",
            f"GRANT SELECT ON bi_compat.{table} TO superset_ro;",
            "",
        ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed SQL is stale")
    args = ap.parse_args()
    sql = render(yaml.safe_load(RENAME_MAP.read_text(encoding="utf-8")))
    if args.check:
        current = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.exists() else ""
        if current != sql:
            print(f"STALE: {OUT_FILE} does not match rename_map.yaml — re-run without --check", file=sys.stderr)
            return 1
        print("OK: bi_compat.sql is up to date")
        return 0
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(sql, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
